# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, base64String, filepath, utf8String }:

cabal.mkDerivation (self: {
  pname = "mySortMaildir";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ base64String filepath utf8String ];
  meta = {
    description = "A small programm to sort maildirs";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
